  
services:
  ####################### Backend #######################
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.ocp
    ports:
      - 8080:8080

  ####################### Frontend #######################
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.ocp
    ports:
      - 8080:8080