  
services:
  ####################### Backend #######################
  backend:
    container_name: pims-api
    build:
      context: backend
      dockerfile: Dockerfile.ocp
    ports:
      - 8080:8080

  ####################### Frontend #######################
  frontend:
    stdin_open: true
    tty: true
    restart: 'no'
    container_name: pims-app
    build:
      context: frontend
      dockerfile: Dockerfile.ocp
    ports:
      - 8080:8080