 # This docker-compose file is used to build the images for the backend and frontend services at the deployment stage.  
services:
  ####################### Backend #######################
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.ocp
    ports:
      - 8080:8080

  ####################### Frontend #######################
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.ocp
    ports:
      - 8080:8080

  ####################### Database Migration ##############

  migration:
    build:
      context: backend
      dockerfile: Dockerfile.migrations
    image: pims-migrations:latest
    