apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    namespace: ${NAMESPACE}
    name: ${APPLICATION_NAME}
    labels:
      app: pims
      env: ${ENVIRONMENT}
      name: ${APPLICATION_NAME}
      role: api
      app.kubernetes.io/part-of: pims-application
      app.openshift.io/runtime: .NET Core
      app.openshift.io/runtime-namespace: ${NAMESPACE}
  spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          namespace: ${NAMESPACE}-tools
          name: '${APPLICATION_NAME}:${IMAGE_TAG}'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: pims
    env: ${ENVIRONMENT}
    role: api
  template:
    metadata:
      name: ${APPLICATION_NAME}
      creationTimestamp: null
      labels:
        app: pims
        env: dev
        instance: ''
        name: ${APPLICATION_NAME}
        role: api
    spec:
      containers:
        - resources:
            limits:
              cpu: 150m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: pims-api
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: 'http://*:8080'
            - name: HealthChecks__LivePath
              value: /health/live
            - name: HealthChecks__ReadyPath
              value: /health/ready
            - name: ConnectionStrings__PIMS
              valueFrom:
                configMapKeyRef:
                  name: pims-api-database
                  key: CONNECTION_STRINGS_PIMS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pims-database
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pims-database
                  key: DB_PASSWORD
            - name: Keycloak__Audience
              valueFrom:
                configMapKeyRef:
                  name: pims-api-sso
                  key: KEYCLOAK_AUDIENCE
            - name: Keycloak__Authority
              valueFrom:
                configMapKeyRef:
                  name: pims-api-sso
                  key: KEYCLOAK_AUTHORITY
            - name: Keycloak__Admin__Authority
              valueFrom:
                configMapKeyRef:
                  name: pims-api-sso
                  key: KEYCLOAK_ADMIN_AUTHORITY
            - name: Keycloak__Secret
              valueFrom:
                secretKeyRef:
                  name: pims-api-sso
                  key: KEYCLOAK_SECRET
            - name: Keycloak__ServiceAccount__Secret
              valueFrom:
                secretKeyRef:
                  name: pims-api-sso
                  key: KEYCLOAK_SERVICE_ACCOUNT_SECRET
            - name: Ches__Username
              valueFrom:
                secretKeyRef:
                  name: pims-api-ches
                  key: CHES_USERNAME
            - name: Ches__Password
              valueFrom:
                secretKeyRef:
                  name: pims-api-ches
                  key: CHES_PASSWORD
            - name: Geocoder__Key
              valueFrom:
                secretKeyRef:
                  name: pims-api-geocoder
                  key: GEOCODER_KEY
            - name: ElasticConfiguration__Password
              valueFrom:
                secretKeyRef:
                  name: pims-api-elasticsearch
                  key: ELASTIC_PASSWORD
            - name: Ches__EmailEnabled
              value: 'true'
            - name: Ches__EmailAuthorized
              value: 'false'
            - name: Elastic__Uri
              value: 'https://pims-elastic.apps.silver.devops.gov.bc.ca/'
            - name: Elastic__Username
              value: elastic
            - name: Elastic__Password
              valueFrom:
                secretKeyRef:
                  name: pims-api-elasticsearch
                  key: ELASTIC_PASSWORD
            - name: Notifications__SendAllNow
              value: 'false'
            - name: Keycloak__FrontendClientId
              value: pims-frontend-4391
            - name: Ltsa__IntegratorUsername
              valueFrom:
                secretKeyRef:
                  name: pims-api-ltsa
                  key: INTEGRATOR_USERNAME
            - name: Ltsa__IntegratorPassword
              valueFrom:
                secretKeyRef:
                  name: pims-api-ltsa
                  key: INTEGRATOR_PASSWORD
            - name: Ltsa__UserName
              valueFrom:
                secretKeyRef:
                  name: pims-api-ltsa
                  key: USERNAME
            - name: Ltsa__UserPassword
              valueFrom:
                secretKeyRef:
                  name: pims-api-ltsa
                  key: USER_PASSWORD
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/ec1236-tools/pims-api@sha256:5b2fa6df235e4cc5fd84a3aa31c09732f1ced46315158328a36b80e9b9805580
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler


parameters:
  - description: Application Name
    displayName: AppName
    name: APPLICATION_NAME
    required: true
    value: pims-api
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: dev
  - description: Namespace
    displayName: Namespace
    name: NAMESPACE
    required: true
    value: ec1236-dev
  - description: ImageTag
    displayName: ImageTag
    name: IMAGE_TAG
    required: true