name: build-deploy-api

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:
    
jobs:
    PIMS-API-Build-Tag-Push:
      environment: dev
      runs-on: ubuntu-latest
      steps:
        # check out the repo
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
          
        # login to the Openshift Cluster
        - name: Login to Openshift
          uses: redhat-actions/oc-login@v1
          with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
            openshift_token: ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}
            namespace: ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}
            
        # Login to BC Gov Docker Image Repository
        - name: Login to Openshift Docker
          run : |
            docker login ${{ secrets.PUBLIC_IMAGE_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_NAME }} -p ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}

        # Build the API Image
        - name: Build API Image
          run: |
            docker-compose -f docker-compose.prod.yml build backend

        - name: Tag API Image
          run: |
            docker tag pims_backend ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/pims-api:dev

        # Push the API Image
        - name: Push API Image
          run: |
            docker push ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/pims-api:dev
          
    deploy:
      name: Deploy to OpenShift
      runs-on: ubuntu-latest
      needs: [ PIMS-API-Build-Tag-Push ]
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3 
      
        - name: Login to OpenShift
          uses: redhat-actions/oc-login@v1
          with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
            openshift_token: ${{ secrets.OPENSHIFT_SA_DEV_TOKEN }}
            namespace: ${{ secrets.OPENSHIFT_DEV_NAMESPACE }}

        - name: Deploy from DeploymentConfig
          env:
            OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_DEV_NAMESPACE }}
            APPLICATION_NAME: "pims-api"
            DEPLOYMENT_CONFIG: "api-dc-template.yaml"
            IMAGE_REPOSITORY: ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}
          run: |
            oc process -f /home/runner/work/PIMS/PIMS/openshift/templates/api-dc-template.yaml --namespace="ec1236-dev"  | \
            oc apply -f -
