name: Api Image Build on PR

on:
  pull_request:
    types: [opened, synchronize, ready_for_review] # Triggered by opened or changed pull requests.
    branches: [main]
    paths:
      - 'backend/**' # Triggers on changes to files in the frontend/ directory.  
    
jobs:
  PIMS-API-Build-Tag-Push:
      environment: dev
      runs-on: ubuntu-latest
      steps:
        # check out the repo
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
    
          
        # login to the Openshift Cluster
        - name: Login to Openshift
          uses: redhat-actions/oc-login@v1
          with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
            openshift_token: ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}
            namespace: ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}
            
        # Login to BC Gov Docker Image Repository
        - name: Login to Openshift Docker
          run : |
            docker login ${{ secrets.PUBLIC_IMAGE_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_NAME }} -p ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}

        # Build the API Image
        - name: Build API Image
          run: |
            docker-compose -f docker-compose.prod.yml build backend

        - name: Tag API Image
          run: |
            docker tag pims_backend ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/pims-api:${{github.event.pull_request.number}}

        # Push the API Image
        - name: Push API Image
          run: |
            docker push ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/pims-api:${{github.event.pull_request.number}}

        - name: Add Comment To the PR
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
               body: "🚀 **Deployment Information**\n\nThe API Image has been built with the tag: **`${{github.event.pull_request.number}}`**. Please make sure to utilize this specific tag when promoting these changes to the TEST and PROD environments during the API deployment."
              })
