name : Update table in wiki

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag'
        required: true

env:
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}
    
jobs:
  update-wiki-table:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone wiki repository
        run: |
          echo "Cloning wiki repo https://github.com/$GITHUB_REPOSITORY.wiki.git"
          git clone "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git" ./wiki
      
      - name: print current directory
        run: |
          ls
          cd wiki
          ls
