name : Update table in wiki

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag'
        required: true

env:
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}
    
jobs:
  update-wiki-table:
    runs-on: ubuntu-latest
    steps:
      - name : Clone wiki
        uses: actions/checkout@v3
        with:
          repository: 'ManishSihag/PIMS.wiki'
          path: './wiki'
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Update Wiki Table
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            // Read the current content of the Wiki page
            const wikiPath = '/home/runner/work/PIMS/PIMS/wiki/image-tags.md';
            let wikiContent = fs.readFileSync(wikiPath, 'utf-8');

            // Parse the table content
            let tableRows = wikiContent.split('\n');
            let apiRow = tableRows[2].split('|');
            
            // Update the value in Row 1, Col 2
            apiRow[3] = ` ${process.env.IMAGE_TAG} `;  // Use the dynamic value from the GitHub Action output
            
            // Assemble the updated table
            tableRows[2] = apiRow.join('|');
            let updatedContent = tableRows.join('\n');

            // Write the updated content back to the Wiki page
            fs.writeFileSync(wikiPath, updatedContent);

      - name: Commit and push changes
        run: |
          cd ./home/runner/work/PIMS/PIMS/wiki
          git config --local user.email "$email"
          git config --local user.name "$author" 
          git add .
          if git diff-index --quiet HEAD; then
            echo "Nothing changed"
            exit 0
          fi

          echo "Pushing changes to wiki"
          git commit -m "$message" && git push "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git"

