name : Update table in wiki

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag'
        required: true

env:
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}
    
jobs:
  update-wiki-table:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone wiki repository
        run: |
          echo "Cloning wiki repo https://github.com/$GITHUB_REPOSITORY.wiki.git"
          git clone "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git" ./wiki
      
      - name: Setup pyhton
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run update wiki python script
        run: python ./.github/helpers/update-wiki-table.py ./wiki/Image-tags.md API "Latest Build Image Tag" "${IMAGE_TAG}"

      - name: Commit and push changes to wiki
        run: |
          cd ./wiki
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "Nothing changed"
            exit 0
          fi
          echo "Pushing changes to wiki"
          git commit -m "value ploulated at image build api" && git push "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git"


