#login to vault

name: Vault

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.developer.gov.bc.ca
          caCertificate : ${{ secrets.VAULT_CA_CERT }}
          token: ${{ secrets.VAULT_SA_TOKEN }}
          secrets: |
            ec1236-non-prod/data/helloworld hi | HI_STRING
    
      - name: Print Secrets
        env:
          HI_STRING: ${{ env.HI_STRING }}
        run: |
          echo $HI_STRING
